apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: guestbook
  name: guestbook
spec:
  replicas: 3
  selector:
    matchLabels:
      app: guestbook
      tier: frontend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: guestbook
        tier: frontend
    spec:
      containers:
      - name: gb-frontend
        image: gb-frontend:v5
        env: 
        - name: GET_HOSTS_FROM
          value: "dns"
        ports:
        - containerPort: 80
        resources: 
          requests: 
            cpu: 100m
            memory: 100Mi
status: {}
