apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: redis-lider
    role: lider
    tier: backend
  name: redis-lider
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis-lider
    role: lider
    tier: backend
status:
  loadBalancer: {}
