apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: redis-seguidor
    role: seguidor
    tier: backend
  name: redis-seguidor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redis-seguidor
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: redis-seguidor
        role: seguidor
        tier: backend
    spec:
      containers:
      - image: redis:6.0.5
        name: redis
        ports:
        - containerPort: 6379
        resources: {}
status: {}
