apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: redis-seguidor
    role: seguidor
    tier: backend
  name: redis-seguidor
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis-seguidor
    role: seguidor
    tier: backend
status:
  loadBalancer: {}
